export const smarthr_custom_fields = {
  workplace_address_postal_code: '郵便番号',
  workplace_address_address: '住所',
  workplace_address_country_number: '勤務地 国番号',
  workplace_address_zip_code: '勤務地郵便番号',
  workplace_address_prefecture: '職場所在地 県',
  workplace_address_city: '職場所在地の都市',
  workplace_address_building: '職場所在地ビル',
  workplace_address_literal_yomi: '職場所在地リテラル（読み）',
  probation_period_start: '始期',
  probation_period_end: '終期',
  //work_hours: '就業時間',
  work_hours_starting_time: '開始時刻',
  work_hours_closing_time: '終業時間',
  work_hours_break_time: '休憩時間',
  work_hours_work_type: '勤務形態',
  work_hours_holiday: '休日',
  wages_display_of_fixed_premiums: '固定割増の表示',
  wages_annual_salary: '年俸額',
  wages_monthly: '月額',
  wages_fixed_premium: '固定割増賃金',
  wages_fixed_overtime_hours: '月間固定残業時間',
  commuting_allowance_monthly: '通勤手当(1ヶ月) ',
  allowance_1: '諸手当① (備考)',
  allowance_2: '諸手当②（諸手当①以外の手当）',
  commuting_allowance_daily: '通勤手当(1日) ',
  employment_insurance: '雇用保険加入有無',
  social_insurance: '社会保険加入有無',
  salary_classification: '給与区分',
  trial_start_date: '始期',
  trial_end_date: '終期',
  position_allowance: '職位手当',
  managers_allowance: '責任者手当',
  special_allowace: '特別手当',
  relocation_allowance: '赴任手当',
  vehicle_allowance: '車両手当',
  other_allowance: 'その他手当'
};