export const CHANGE_KEY_MAP = {
    "コード": "code",
    "社員番号": "code",
    "氏名": "name",
    "氏　名": "name",
    "異動前": "prevPosition",
    "異動後": "newPosition",
    "異動日": "effectivityDate",
    "異動適用日": "effectivityDate",
    "新雇用区分": "newEmploymentType",
    "業務内容": "jobDescription",
    "給与額": "salaryAmount",
    "基本給": "monthlyBaseSalary",
    "月間勤務時間数": "monthlyWorkingHours",
    "固定残業": "fixedOvertime",
    "所属": "department",
    "name": "対象者氏名",
    "新所属部署": "newDepartment",
    "新役職": "newPosition",
    "新給与": "newSalary",
    "職務手当": "jobAllowance",
    transferDetails: "移転の詳細",
    effectivityDate: "変更日/異動日",
    classification: "申請区分",
};

export const CHANGE_CUSTOM_FIELDS = {
    "月額": 'salaryAmount',
    "申請区分": 'classification',
    "移転の詳細": 'transferDetails',
    "新所属部署": 'newDepartment',
    "新役職": 'newPosition',
    "新給与": 'newSalary',
    "職務手当": 'jobAllowance',
    classification: "転送の分類",
    transferDetails: "移転の詳細",
    effectivityDate: "移転の効力発生日",
};